[package]
name = "propag"
version = "0.1.0"
authors = ["GregoireHENRY <gregoire.henry@ipsa.fr>"]
edition = "2018"

[dependencies]
ndarray = "0.13.1"
itertools = "0.9.0"
crossbeam = "0.7.3"
log = "0.4.8"
simplelog = "0.8.0"

[profile.release]
lto = true
debug = true
